language:                 node_js

node_js:                  lts/*

cache:
    - npm
    - yarn

before_install:
    - npm install --global yarn

install:
    - yarn install --non-interactive --production false

script:
    - node cli
    - yarn build
    - if [ -n "$TRAVIS_TAG" ]; then npm version $TRAVIS_TAG; fi

deploy:
    - provider:           npm
      email:              richiebendall@gmail.com
      skip_cleanup:       true
      api_key:            $npm_token
      on:
          tags:           true
          repo:           Richienb/rosav

    -   provider:         releases
        api_key:          $github_token
        file_glob:        true
        file:             dist/*
        skip_cleanup:     true
        on:
            tags:           true
            repo:           Richienb/rosav
